const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Json,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Follow,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Cnds.OnDestroyed,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.TileMovement.Cnds.CanMoveDirection,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.TileMovement.Acts.SetSpeed,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Follow.Acts.StopFollowing,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetAnimSpeed
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{Array: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{JSON: 0},
	{Keyboard: 0},
	{Audio: 0},
	{buttonHome: 0},
	{buttonSound: 0},
	{level: 0},
	{obj_level_box: 0},
	{txt_Loading: 0},
	{txt_levels: 0},
	{fade_type: 0},
	{fade_time: 0},
	{destiny: 0},
	{Tween: 0},
	{Fade: 0},
	{Sine: 0},
	{loadingLogo: 0},
	{Follow: 0},
	{obj_enemy: 0},
	{moving: 0},
	{can_move: 0},
	{direction: 0},
	{dead: 0},
	{playback_rate: 0},
	{TileMovement: 0},
	{Timer: 0},
	{obj_player: 0},
	{anim_player: 0},
	{ScrollTo: 0},
	{obj_camera: 0},
	{start_game: 0},
	{obj_game_manager: 0},
	{Solid: 0},
	{tile_walls: 0},
	{obj_coin: 0},
	{rotate_value: 0},
	{init_pos: 0},
	{distance_orbit: 0},
	{obj_player_particles: 0},
	{obj_door: 0},
	{obj_spikes: 0},
	{Anchor: 0},
	{fam_hud_buttons: 0},
	{fam_interactive_buttons: 0},
	{fam_tile_colors: 0},
	{fam_obj_colors: 0},
	{fam_deadly: 0},
	{levels_unlocked: 0},
	{Loaded: 0},
	{Fading: 0},
	{fadeTime: 0},
	{sound_off: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	buttonHome: class extends self.ISpriteInstance {},
	buttonSound: class extends self.ISpriteInstance {},
	obj_level_box: class extends self.ISpriteInstance {},
	txt_Loading: class extends self.ISpriteFontInstance {},
	txt_levels: class extends self.ISpriteFontInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	loadingLogo: class extends self.ISpriteInstance {},
	obj_enemy: class extends self.ISpriteInstance {},
	obj_player: class extends self.ISpriteInstance {},
	anim_player: class extends self.ISpriteInstance {},
	obj_camera: class extends self.ISpriteInstance {},
	obj_game_manager: class extends self.ISpriteInstance {},
	tile_walls: class extends self.ITilemapInstance {},
	obj_coin: class extends self.ISpriteInstance {},
	obj_player_particles: class extends self.ISpriteInstance {},
	obj_door: class extends self.ISpriteInstance {},
	obj_spikes: class extends self.ISpriteInstance {},
	fam_hud_buttons: class extends self.ISpriteInstance {},
	fam_interactive_buttons: class extends self.ISpriteInstance {},
	fam_tile_colors: class extends self.ITilemapInstance {},
	fam_obj_colors: class extends self.ISpriteInstance {},
	fam_deadly: class extends self.ISpriteInstance {}
}